# Generated by Django 2.1.10 on 2019-07-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20190716_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='castlestatus_b',
            field=models.CharField(default='both', max_length=8),
        ),
        migrations.AddField(
            model_name='game',
            name='castlestatus_w',
            field=models.CharField(default='both', max_length=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(default='rnbqkbnrpppppppp................................PPPPPPPPRNBQKBNR', max_length=64),
        ),
        migrations.AlterField(
            model_name='game',
            name='move',
            field=models.IntegerField(default=1),
        ),
    ]
